CREATE OR REPLACE FUNCTION 
func_minimum(arr VARIADIC NUMERIC[])
    RETURNS NUMERIC AS
$$
SELECT MIN(value) FROM UNNEST(arr) VALUES(value);
$$
LANGUAGE SQL;

SELECT func_minimum(VARIADIC arr => ARRAY[10.0, -1.0, 5.0, 4.4]);
